name:                tic-tac-toe-backend
version:             0.1.0.0
github:              "githubuser/tic-tac-toe-backend"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tic-tac-toe-backend#readme>

dependencies:
- base
- random
- classy-prelude
- aeson
- lucid
- stm
- servant-server
- servant-lucid
- wai
- wai-app-static
- warp
- servant-websockets
- websockets
- elm-bridge
- text
- bytestring
- time
- mtl

library:
  source-dirs: src

executables:
  tic-tac-toe-backend-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    default-extensions:
    - NoImplicitPrelude
    dependencies:
    - base
    - tic-tac-toe-backend

tests:
  tic-tac-toe-backend-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - tic-tac-toe-backend
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
